name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/developer-profile-api:latest

      - name: Deploy Docker Container on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/developer-profile-api:latest

            docker stop developer-profile-api || true
            docker rm developer-profile-api || true
            docker image prune -f --filter "label=app=developer-profile-api"

            docker run -d \
              -e PORT=${{ secrets.PORT }} \
              -e MONGO_URI=${{ secrets.MONGO_URI }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DEFAULT_ID=${{ secrets.DEFAULT_ID }} \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              --name developer-profile-api -p 8080:8080 \
              --label app=developer-profile-api \
              ${{ secrets.DOCKER_USERNAME }}/developer-profile-api:latest
